name = "Vitae"
license = "MIT"
licenselink = "https://github.com/dwaiba/vitae/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/dwaiba/vitae/"
tags = ["cv", "resume"]
features = ["one page", "resume"]
min_version = 0.17

[author]
  name = "dwaiba"
  homepage = "https://github.com/dwaiba/"
